-- The readiness catalogue is now seeded via migration 202607020041_catalogue_seed.sql
-- so it deploys to every environment (a hosted `supabase db push`, not only a local
-- `supabase db reset`). Kept intentionally empty to avoid double-seeding on reset.
