"use client";
import { useEffect, useRef, useState } from "react";
import { Card, PageIntro, Pill, Stat } from "@/components/ui";
import { Icon } from "@/components/icons";

type Risk={title:string;owner:string;category:string;l:number;i:number;resL:number;resI:number;treatment:string;review:string;evidence:string;status:string};
const STORAGE="compliancehub-demo-risks";
const seed:Risk[]=[
 {title:"Ransomware affects shared drive",owner:"Priya Shah",category:"Technological",l:4,i:5,resL:2,resI:4,treatment:"Mitigate",review:"2026-06-18",evidence:"Endpoint protection and tested backups reduce exposure.",status:"In progress"},
 {title:"Supplier exposes customer data",owner:"Tom Reilly",category:"Organisational",l:3,i:5,resL:2,resI:3,treatment:"Mitigate",review:"2026-07-08",evidence:"Supplier review is scheduled.",status:"Open"},
 {title:"Unauthorised access after leaver",owner:"Dan Okoro",category:"People",l:3,i:4,resL:2,resI:2,treatment:"Mitigate",review:"2026-07-21",evidence:"HR offboarding checklist is in use.",status:"In progress"},
 {title:"Backups cannot be restored",owner:"Priya Shah",category:"Technological",l:3,i:5,resL:1,resI:5,treatment:"Mitigate",review:"2026-06-24",evidence:"Restore exercise is overdue.",status:"Open"}
];
const sev=(n:number)=>n>=15?"Critical":n>=10?"High":n>=5?"Medium":"Low";
const scores=[1,2,3,4,5];

export default function Risks(){
 const [risks,setRisks]=useState(seed),[filter,setFilter]=useState("All"),[panel,setPanel]=useState(false),[resetOpen,setResetOpen]=useState(false),[cell,setCell]=useState<string>();
 const [likelihood,setLikelihood]=useState(3),[impact,setImpact]=useState(3),[resL,setResL]=useState(2),[resI,setResI]=useState(2);
 const opener=useRef<HTMLButtonElement>(null),firstField=useRef<HTMLInputElement>(null);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{const saved=localStorage.getItem(STORAGE);if(saved)setRisks(JSON.parse(saved))}catch{}},0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{if(panel){firstField.current?.focus();const close=(e:KeyboardEvent)=>{if(e.key==="Escape")setPanel(false)};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)}else opener.current?.focus()},[panel]);
 function persist(next:Risk[]){setRisks(next);try{localStorage.setItem(STORAGE,JSON.stringify(next))}catch{}}
 function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);persist([...risks,{title:String(d.get("title")),owner:String(d.get("owner")),category:String(d.get("category")),l:likelihood,i:impact,resL,resI,treatment:String(d.get("treatment")),review:String(d.get("review")),evidence:String(d.get("evidence")),status:"Open"}]);setPanel(false)}
 function reset(){persist(seed);setCell(undefined);setFilter("All");setResetOpen(false)}
 const visible=risks.filter(r=>(filter==="All"||sev(r.l*r.i)===filter)&&(!cell||cell===`${r.l}-${r.i}`));
 const high=risks.filter(r=>r.l*r.i>=10).length,progress=risks.filter(r=>r.status==="In progress").length;
 return <><PageIntro title="Risk register" body="Record, prioritise and treat the risks that matter to Northstar Labs." action={<div className="button-group"><button className="button secondary" onClick={()=>setResetOpen(true)}>Reset demo data</button><button ref={opener} className="button primary" onClick={()=>setPanel(true)}><Icon name="plus"/>Add a risk</button></div>}/>
 <div className="stats-grid risk-stats"><Stat label="OPEN RISKS" value={risks.length} detail="across the organisation"/><Stat label="HIGH / CRITICAL" value={high} detail="need attention" tone="red"/><Stat label="IN PROGRESS" value={progress} detail="treatments underway" tone="green"/><Stat label="OVERDUE REVIEW" value={risks.filter(r=>r.review<"2026-07-02").length} detail="review dates passed" tone="amber"/></div>
 <Card className="heat-card"><div className="card-head"><div><h3>Inherent risk heat map</h3><p>Select a square to filter the register below</p></div><div className="heat-legend"><span><i className="low"/>Low</span><span><i className="medium"/>Medium</span><span><i className="high"/>High</span><span><i className="critical"/>Critical</span></div></div><div className="heat-layout"><b className="axis y">LIKELIHOOD</b><div className="heat-labels ylabels">{[5,4,3,2,1].map(x=><span key={x}>{x}</span>)}</div><div className="risk-heat">{[5,4,3,2,1].flatMap(l=>scores.map(i=>{const count=risks.filter(r=>r.l===l&&r.i===i).length;return <button key={`${l}-${i}`} aria-label={`Likelihood ${l}, impact ${i}`} aria-pressed={cell===`${l}-${i}`} className={`${sev(l*i).toLowerCase()} ${cell===`${l}-${i}`?"selected":""}`} onClick={()=>setCell(cell===`${l}-${i}`?undefined:`${l}-${i}`)}>{count||""}</button>}))}</div><div className="heat-labels xlabels">{scores.map(x=><span key={x}>{x}</span>)}</div><b className="axis x">IMPACT</b></div></Card>
 <Card className="risk-table"><div className="table-tools"><div className="segmented">{["All","Low","Medium","High","Critical"].map(x=><button key={x} aria-pressed={filter===x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div>{cell&&<button onClick={()=>setCell(undefined)} className="clear-filter">Clear heat-map filter ×</button>}<span>{visible.length} of {risks.length} risks</span></div><div className="data-table-wrap"><table><thead><tr><th>Risk</th><th>Owner</th><th>Treatment</th><th>Inherent</th><th>Residual</th><th>Review</th><th>Status</th></tr></thead><tbody>{visible.map(r=><tr key={r.title}><td><b>{r.title}</b><small>{r.category}</small></td><td>{r.owner}</td><td>{r.treatment}</td><td><Pill tone={sev(r.l*r.i).toLowerCase()}>{sev(r.l*r.i)}</Pill></td><td><Pill tone={sev(r.resL*r.resI).toLowerCase()}>{sev(r.resL*r.resI)}</Pill></td><td className={r.review<"2026-07-02"?"overdue":""}>{r.review<"2026-07-02"?"Overdue · ":""}{new Date(`${r.review}T12:00:00`).toLocaleDateString("en-GB",{day:"2-digit",month:"short"})}</td><td>{r.status}</td></tr>)}</tbody></table></div></Card>
 {panel&&<div className="drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setPanel(false)}}><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="risk-dialog-title"><button className="drawer-close" aria-label="Close risk editor" onClick={()=>setPanel(false)}>×</button><h2 id="risk-dialog-title">Add a risk</h2><p>Describe the risk, score it and record the treatment you intend to apply.</p><form onSubmit={add}><label>Risk description<input ref={firstField} name="title" required placeholder="For example: Customer data is exposed…"/></label><label>Owner<input name="owner" required placeholder="Name or role"/></label><div className="form-grid"><label>Category<select name="category"><option>Organisational</option><option>People</option><option>Physical</option><option>Technological</option></select></label><label>Treatment<select name="treatment"><option>Mitigate</option><option>Avoid</option><option>Transfer</option><option>Accept</option></select></label><label>Likelihood<select value={likelihood} onChange={e=>setLikelihood(+e.target.value)}>{scores.map(x=><option value={x} key={x}>{x}</option>)}</select></label><label>Impact<select value={impact} onChange={e=>setImpact(+e.target.value)}>{scores.map(x=><option value={x} key={x}>{x}</option>)}</select></label><label>Residual likelihood<select value={resL} onChange={e=>setResL(+e.target.value)}>{scores.map(x=><option value={x} key={x}>{x}</option>)}</select></label><label>Residual impact<select value={resI} onChange={e=>setResI(+e.target.value)}>{scores.map(x=><option value={x} key={x}>{x}</option>)}</select></label></div><label>Review date<input name="review" type="date" required defaultValue="2026-12-01"/></label><label>Evidence or notes<textarea name="evidence" placeholder="Controls, actions or supporting evidence…"/></label><div className="score-callout">Inherent score <Pill tone={sev(likelihood*impact).toLowerCase()}>{sev(likelihood*impact)} · {likelihood*impact}</Pill><span>Residual</span><Pill tone={sev(resL*resI).toLowerCase()}>{sev(resL*resI)} · {resL*resI}</Pill></div><button className="button primary" type="submit">Add risk</button></form></aside></div>}
 {resetOpen&&<div className="drawer-backdrop confirm-backdrop"><div className="confirm" role="alertdialog" aria-modal="true" aria-labelledby="reset-title"><h2 id="reset-title">Reset demo risk data?</h2><p>This removes your browser-only changes and restores the Northstar Labs sample risks.</p><div><button className="button secondary" onClick={()=>setResetOpen(false)}>Cancel</button><button className="button primary" onClick={reset}>Yes, reset demo</button></div></div></div>}
 </>;
}
