import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { createTeamFixture, signIn, teamTestEnabled } from "./helpers/team-workspace";

test.skip(!teamTestEnabled, "Requires the isolated fictional local database.");

test("asset import requires a fresh preview after mapping changes and consumes confirmation", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  const { actors } = await createTeamFixture();
  await page.setViewportSize(testInfo.project.name === "mobile" ? { width: 393, height: 851 } : { width: 1440, height: 1000 });
  await signIn(page, actors[0]);
  await page.goto("/app/assets/import");
  const csv = "Asset Reference,Asset Description,Classification,Value (Criticality)\nAST-PREVIEW-01,Fictional preview service,Confidential,High";
  await page.getByLabel("Workbook file (XLSX or CSV)").setInputFiles({ name: "fictional-assets.csv", mimeType: "text/csv", buffer: Buffer.from(csv) });
  await page.getByRole("button", { name: "Analyse file", exact: true }).click();
  const mapping = page.getByLabel("Map column Asset Description", { exact: true });
  await expect(mapping).toHaveValue("description");
  const selectorBounds = await mapping.boundingBox();
  expect(selectorBounds).not.toBeNull();
  expect(selectorBounds!.x).toBeGreaterThanOrEqual(0);
  expect(selectorBounds!.x + selectorBounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width);
  await page.getByRole("button", { name: "Preview 1 row", exact: true }).click();
  const confirm = page.getByRole("button", { name: "4. Confirm import (1)", exact: true });
  await expect(confirm).toBeVisible();
  await mapping.selectOption("");
  await page.evaluate(() => window.scrollTo({ top: 0, left: 0, behavior: "instant" }));
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0);
  await page.screenshot({ path: testInfo.outputPath("changed-mapping.png"), fullPage: true });
  await expect(confirm).toHaveCount(0);
  await mapping.selectOption("description");
  await expect(confirm).toHaveCount(0);
  await page.getByRole("button", { name: "Preview 1 row", exact: true }).click();
  await expect(confirm).toBeVisible();
  const replacement = "Asset Reference,Asset Description,Classification,Value (Criticality)\nAST-PREVIEW-02,Fictional replacement service,Confidential,High";
  await page.getByLabel("Workbook file (XLSX or CSV)").setInputFiles({ name: "fictional-replacement.csv", mimeType: "text/csv", buffer: Buffer.from(replacement) });
  await expect(confirm).toHaveCount(0);
  await expect(mapping).toHaveCount(0);
  await page.getByRole("button", { name: "Analyse file", exact: true }).click();
  await page.getByRole("button", { name: "Preview 1 row", exact: true }).click();
  await expect(confirm).toBeVisible();
  await confirm.focus();
  await expect(confirm).toBeFocused();
  const accessibility = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa"]).analyze();
  expect(accessibility.violations.filter((item) => item.impact === "critical" || item.impact === "serious")).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await confirm.press("Enter");
  await expect(page.getByRole("heading", { name: "Import complete", exact: true })).toBeVisible();
  await expect(page.getByText("1 row added.", { exact: true })).toBeVisible();
  await expect(confirm).toHaveCount(0);
  await page.evaluate(() => window.scrollTo({ top: 0, left: 0, behavior: "instant" }));
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0);
  await page.screenshot({ path: testInfo.outputPath("import-complete.png"), fullPage: true });
  await page.getByRole("link", { name: "View asset inventory", exact: true }).click();
  await page.getByRole("link", { name: "Fictional replacement service", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Fictional replacement service", exact: true })).toBeVisible();
  await expect(page.getByText("ASSET AST-PREVIEW-02", { exact: true })).toBeVisible();
});
