import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { createTeamFixture, signIn, teamTestEnabled } from "./helpers/team-workspace";

test.skip(!teamTestEnabled, "Requires the isolated fictional local database.");

test("policy ownership survives editing and employees accept only published versions", async ({ browser }, testInfo) => {
  test.setTimeout(120_000);
  const { actors, organisationId, coordinator } = await createTeamFixture();
  const viewport = testInfo.project.name === "mobile" ? { width: 393, height: 851 } : { width: 1440, height: 1000 };
  const operatorContext = await browser.newContext({ viewport });
  const employeeContext = await browser.newContext({ viewport });
  const operator = await operatorContext.newPage();
  const employee = await employeeContext.newPage();
  operator.setDefaultTimeout(20_000); employee.setDefaultTimeout(20_000);
  try {
    await signIn(operator, actors[0]);
    await operator.goto("/app/policies/new");
    await operator.getByRole("textbox", { name: "Reference", exact: true }).fill("POL-CYCLE-01");
    await operator.getByRole("textbox", { name: "Title", exact: true }).fill("Quarterly access policy — fictional");
    await operator.getByRole("combobox", { name: "Owner", exact: true }).selectOption(actors[1].id);
    await operator.getByRole("textbox", { name: "Policy content", exact: true }).fill("Fictional access review responsibilities for the company.");
    await operator.getByRole("button", { name: "Create policy", exact: true }).click();
    await expect(operator).toHaveURL(/\/app\/policies\/[0-9a-f-]+$/);
    const policyUrl = operator.url();
    await expect(operator.getByRole("button", { name: "I accept this policy", exact: true })).toHaveCount(0);
    await expect(operator.getByText(/Personal acceptance is available only while this policy is approved/)).toBeVisible();
    await operator.getByText("Edit policy", { exact: true }).click();
    const owner = operator.getByRole("combobox", { name: "Policy owner", exact: true });
    await expect(owner).toHaveValue(actors[1].id);
    await operator.getByRole("textbox", { name: "Title", exact: true }).fill("Annual access policy — fictional");
    await operator.getByRole("button", { name: "Save changes", exact: true }).click();
    await expect(operator.getByRole("status")).toHaveText("Policy changes saved.");
    await expect(operator.getByRole("heading", { name: "Annual access policy — fictional", exact: true })).toBeVisible();
    await operator.reload();
    await operator.getByText("Edit policy", { exact: true }).click();
    await expect(owner).toHaveValue(actors[1].id);
    await owner.selectOption(actors[2].id);
    await operator.getByRole("button", { name: "Save changes", exact: true }).click();
    await expect(operator.getByRole("status")).toHaveText("Policy changes saved.");
    await expect(owner).toHaveValue(actors[2].id);
    await operator.reload();
    await operator.getByText("Edit policy", { exact: true }).click();
    await expect(owner).toHaveValue(actors[2].id);
    await owner.selectOption("");
    await operator.getByRole("button", { name: "Save changes", exact: true }).click();
    await expect(operator.getByRole("status")).toHaveText("Policy changes saved.");
    await operator.reload();
    await operator.getByText("Edit policy", { exact: true }).click();
    await expect(owner).toHaveValue("");
    await owner.selectOption(actors[1].id);
    await operator.getByRole("button", { name: "Save changes", exact: true }).click();
    await expect(operator.getByRole("status")).toHaveText("Policy changes saved.");
    await operator.screenshot({ path: testInfo.outputPath("policy-owner-and-draft-guidance.png"), fullPage: true });
    await operator.getByRole("button", { name: "Approve policy", exact: true }).click();
    await expect(operator.getByRole("button", { name: "I accept this policy", exact: true })).toBeVisible();
    await signIn(employee, actors[1]);
    await employee.goto(policyUrl);
    await expect(employee.getByText("Edit policy", { exact: true })).toHaveCount(0);
    await employee.getByRole("button", { name: "I accept this policy", exact: true }).click();
    await expect(employee.getByText(/You have accepted the current version\./)).toBeVisible();
    await employee.reload();
    await expect(employee.getByText(/You have accepted the current version\./)).toBeVisible();
    await employee.screenshot({ path: testInfo.outputPath("employee-policy-acceptance.png"), fullPage: true });
    expect(await employee.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
    const accessibility = await new AxeBuilder({ page: employee }).withTags(["wcag2a", "wcag2aa"]).analyze();
    await testInfo.attach("policy-accessibility", { body: JSON.stringify(accessibility.violations, null, 2), contentType: "application/json" });
    expect(accessibility.violations.filter((item) => item.impact === "critical" || item.impact === "serious")).toEqual([]);
    const { data: saved, error } = await coordinator.from("policies").select("owner_id").eq("organisation_id", organisationId).eq("reference", "POL-CYCLE-01").single();
    expect(error).toBeNull(); expect(saved?.owner_id).toBe(actors[1].id);
  } finally {
    await Promise.allSettled([operatorContext.close(), employeeContext.close()]);
  }
});

test("risk review exposes its recorded asset context in both directions", async ({ page }, testInfo) => {
  test.setTimeout(90_000); page.setDefaultTimeout(20_000);
  const { actors, organisationId, coordinator } = await createTeamFixture();
  const { data: category, error: categoryError } = await coordinator.from("risk_categories").select("id").eq("organisation_id", organisationId).order("position").limit(1).single();
  expect(categoryError).toBeNull();
  const { data: risk, error: riskError } = await coordinator.from("risks").insert({ organisation_id: organisationId, reference: "RSK-CONTEXT-01", category_id: category!.id, title: "Unreviewed production access — fictional", description: "Fictional operational review of production access.", likelihood: 3, impact: 4, residual_likelihood: 2, residual_impact: 3, treatment: "mitigate", created_by: actors[0].id }).select("id").single();
  expect(riskError).toBeNull();
  const { data: asset, error: assetError } = await coordinator.from("assets").insert({ organisation_id: organisationId, reference: "AST-CONTEXT-01", description: "Production service — fictional", owner_id: actors[1].id, created_by: actors[0].id }).select("id").single();
  expect(assetError).toBeNull();
  const { error: linkError } = await coordinator.from("asset_risks").insert({ organisation_id: organisationId, risk_id: risk!.id, asset_id: asset!.id, created_by: actors[0].id });
  expect(linkError).toBeNull();
  await signIn(page, actors[0]);
  await page.goto(`/app/assets/${asset!.id}`);
  await page.getByRole("link", { name: /RSK-CONTEXT-01/ }).click();
  await expect(page.getByRole("heading", { name: "Linked assets", exact: true })).toBeVisible();
  const assetLink = page.getByRole("link", { name: /AST-CONTEXT-01/ });
  await expect(assetLink).toBeVisible();
  await assetLink.focus();
  await expect(assetLink).toBeFocused();
  await page.screenshot({ path: testInfo.outputPath("risk-linked-assets.png"), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  await assetLink.press("Enter");
  await expect(page).toHaveURL(new RegExp(`/app/assets/${asset!.id}$`));
  await expect(page.getByRole("heading", { name: "Production service — fictional", exact: true })).toBeVisible();
});
