import Link from "next/link";
import { Icon } from "@/components/icons";
import { Progress, Ring } from "@/components/ui";

export default function Landing() {
  return <div className="landing">
    <header className="landing-nav"><Link className="brand" href="/"><span className="brand-mark"><Icon name="shield"/></span><span>ComplianceHub</span></Link><div><Link className="button secondary" href="/demo/dashboard">Create your workspace</Link><Link className="button primary" href="/demo/dashboard">Try the demo</Link></div></header>
    <main>
      <section className="hero"><div className="hero-copy"><span className="hero-tag"><i/>ISO 27001 readiness, minus the jargon</span><h1>Get your security readiness under control.</h1><p>Answer plain-English questions about how your company works. ComplianceHub turns your answers into the security-readiness documents auditors expect — a gap assessment, Statement of Applicability, and risk register.</p><div className="hero-buttons"><Link className="button primary large" href="/demo/dashboard">Try the demo <Icon name="arrow"/></Link><Link className="button secondary large" href="/demo/dashboard">Create your workspace</Link></div><small><Icon name="check"/> No credit card · Set up in minutes · Built for small UK teams</small></div>
      <div className="hero-preview"><div className="preview-head"><b>Northstar Labs — Readiness</b><span>Demo</span></div><div className="preview-score"><Ring value={62}/><div>{[["Organisational",70],["Technological",55],["People",48]].map(([x,n])=><div className="mini-progress" key={x}><label><span>{x}</span><b>{n}%</b></label><Progress value={Number(n)}/></div>)}</div></div><div className="preview-stats"><span><b>5</b>Priority gaps</span><span><b className="amber-text">3</b>High risks</span><span><b className="green-text">75%</b>Complete</span></div></div></section>
      <section className="how"><span>HOW IT WORKS</span><h2>Three steps to organised</h2><div>{[["clipboard","1","Answer simple questions","Tell us how your team handles access, backups, suppliers and other everyday security practices."],["file","2","Review your documents","We turn your answers into a clear gap report and an editable Statement of Applicability."],["alert","3","Manage what matters","Track risks, owners and review dates in one place — with an audit-friendly history."]].map(([icon,n,t,d])=><article key={n}><i><Icon name={icon}/></i><em>{n}</em><h3>{t}</h3><p>{d}</p></article>)}</div></section>
      <section className="open-source"><Icon name="lock"/><div><h2>Built in the open. Your data stays yours.</h2><p>Free and open-source, with transparent methods and no certification claims. Deploy it yourself or use the hosted beta.</p></div><a href="https://github.com" target="_blank" rel="noreferrer">View on GitHub <Icon name="arrow"/></a></section>
    </main><footer className="landing-foot"><span>© 2026 ComplianceHub · MIT licensed</span><span>ComplianceHub does not provide certification or legal advice.</span></footer>
  </div>;
}
