"use client";
import { useRef, useState } from "react";

type Question = { id: string; code: string; prompt: string };
type Response = { question_id: string; answer: string | null; evidence_note: string };

export function AssessmentResponseList({ sessionId, questions, initialRevision, responses }: { sessionId: string; questions: Question[]; initialRevision: number; responses: Response[] }) {
  const revision = useRef(initialRevision); const queue = useRef(Promise.resolve()); const [states,setStates]=useState<Record<string,string>>({});
  function save(questionId: string, form: HTMLFormElement) { const values=Object.fromEntries(new FormData(form)); setStates(s=>({...s,[questionId]:"saving"})); queue.current=queue.current.then(async()=>{ const result=await fetch("/api/app/assessment/response",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId,questionId,answer:values.answer,evidenceNote:values.evidenceNote,expectedRevision:revision.current})}); const body=await result.json(); if(!result.ok){setStates(s=>({...s,[questionId]:result.status===409?"conflict — reload required":"save failed"}));return;} revision.current=body.revision; setStates(s=>({...s,[questionId]:"saved"})); }); }
  return <div className="space-y-4">{questions.map(question=>{const response=responses.find(r=>r.question_id===question.id);return <form key={question.id} className="rounded-xl border bg-white p-5"><div className="flex justify-between gap-3"><label className="font-semibold">{question.code}: {question.prompt}</label><span aria-live="polite" className="text-xs text-slate-500">{states[question.id]??""}</span></div><select name="answer" defaultValue={response?.answer??""} onChange={e=>save(question.id,e.currentTarget.form!)} className="mt-4 rounded border px-3 py-2"><option value="" disabled>Select answer</option><option value="yes">Yes</option><option value="partially">Partially</option><option value="no">No</option><option value="not_applicable">Not applicable</option></select><textarea name="evidenceNote" defaultValue={response?.evidence_note} onBlur={e=>save(question.id,e.currentTarget.form!)} maxLength={10000} placeholder="Evidence note" className="mt-3 block w-full rounded border p-3"/></form>})}</div>;
}
