// Starter policy templates for a new organisation. This is a plain domain module
// (NOT a "use server" file) so it can be imported by server components to pre-fill
// the authoring form. Every body below is original en-GB prose written for this
// project — a generic, sensible starting point the organisation is expected to
// edit before approving. Nothing here is copied from any ISO toolkit or standard.
//
// The reference/title/body must satisfy the same limits the create action enforces
// (reference ≤ 40, title ≤ 200, body ≤ 100,000) — see policyInputSchema.

export type PolicyTemplate = {
  slug: string;
  reference: string;
  title: string;
  summary: string;
  body: string;
};

export const POLICY_TEMPLATES: PolicyTemplate[] = [
  {
    slug: "information-security",
    reference: "POL-001",
    title: "Information Security Policy",
    summary: "The top-level statement of intent that anchors the whole information security management system.",
    body: [
      "Purpose",
      "This policy sets out our commitment to protecting the confidentiality, integrity and availability of the information we hold, and to running an information security management system that is reviewed and improved over time.",
      "",
      "Scope",
      "This policy applies to every employee, contractor and third party who handles our information or uses our systems, across all of the locations, devices and services we operate.",
      "",
      "Policy statements",
      "We identify the information and systems that matter to the business and assess the risks to them on a regular basis. We put proportionate controls in place to manage those risks and we hold people accountable for following them. We meet the legal, regulatory and contractual obligations that apply to our information, and we expect security to be considered in day-to-day decisions rather than treated as an afterthought. Security events and weaknesses are reported promptly and handled through a defined process.",
      "",
      "Responsibilities",
      "Leadership owns this policy, provides the resources needed to deliver it and reviews its performance. Managers make sure their teams understand and apply it. Everyone is responsible for protecting the information they work with and for reporting anything that looks wrong.",
      "",
      "Review",
      "This policy is reviewed at least once a year, and sooner if there is a significant change to the business, its systems or the threats it faces.",
    ].join("\n"),
  },
  {
    slug: "access-control",
    reference: "POL-002",
    title: "Access Control Policy",
    summary: "How access to systems and data is granted, reviewed and removed on a least-privilege basis.",
    body: [
      "Purpose",
      "This policy defines how we control who can reach our systems and data so that people have the access they need to do their job and nothing more.",
      "",
      "Scope",
      "It covers all accounts, applications, networks and data stores we operate, and everyone who is granted access to them.",
      "",
      "Policy statements",
      "Access is granted on the principle of least privilege and is tied to a person's role and current need. New access is approved by an appropriate owner before it is provisioned, and each account belongs to a single identifiable individual wherever possible. Privileged and administrative access is limited to the smallest workable group and is subject to closer scrutiny. Access rights are reviewed at regular intervals and are removed promptly when someone changes role or leaves. Authentication uses strong credentials, and additional verification is required for sensitive or remote access.",
      "",
      "Responsibilities",
      "System owners decide who may hold access to their systems and approve changes. IT provisions and de-provisions access on the basis of those approvals. Managers tell IT when a team member joins, changes role or leaves.",
      "",
      "Review",
      "This policy is reviewed at least once a year and after any significant change to how we manage identities and access.",
    ].join("\n"),
  },
  {
    slug: "acceptable-use",
    reference: "POL-003",
    title: "Acceptable Use Policy",
    summary: "What is and is not acceptable when using company devices, accounts and networks.",
    body: [
      "Purpose",
      "This policy explains how our systems, devices and accounts may be used, so that people can work productively without putting information or the business at risk.",
      "",
      "Scope",
      "It applies to everyone who uses our equipment, software, networks or accounts, whether on our premises, remotely or on a personal device that is permitted for work.",
      "",
      "Policy statements",
      "Our systems are provided mainly for work, and limited personal use is acceptable as long as it is lawful, reasonable and does not interfere with the business. Users must protect the credentials they are given and must not share them or leave sessions unattended. Company information must only be stored and shared using approved services. Installing unapproved software, disabling security controls, or attempting to bypass protections is not permitted. Users must not use our systems to harass others, to access unlawful material, or to send confidential information to people who are not entitled to see it.",
      "",
      "Responsibilities",
      "Every user is responsible for using our systems in line with this policy. Managers set a good example and address misuse. IT provides the approved tools and the guidance needed to use them safely.",
      "",
      "Review",
      "This policy is reviewed at least once a year and whenever the tools or working practices it describes change significantly.",
    ].join("\n"),
  },
  {
    slug: "incident-response",
    reference: "POL-004",
    title: "Incident Response Policy",
    summary: "How security events and incidents are reported, triaged, contained and learned from.",
    body: [
      "Purpose",
      "This policy sets out how we detect, report and respond to information security incidents so that harm is limited and lessons are captured.",
      "",
      "Scope",
      "It applies to any event that may affect the confidentiality, integrity or availability of our information or systems, and to everyone who might notice or handle such an event.",
      "",
      "Policy statements",
      "Anyone who spots a suspected incident or weakness reports it straight away through the channel we publish, without trying to investigate alone. Reported events are triaged and assigned a severity so that effort matches the risk. We act to contain and recover from incidents, keeping a record of what happened and what was done. Where an incident involves personal data or triggers a legal or contractual duty, we notify the relevant people and authorities within the required timeframes. After significant incidents we hold a review to understand the cause and to improve our controls.",
      "",
      "Responsibilities",
      "All staff report incidents promptly. A named responder or team coordinates the response and decides on escalation. Leadership is kept informed of serious incidents and supports any external notification.",
      "",
      "Review",
      "This policy is reviewed at least once a year and after any major incident or exercise.",
    ].join("\n"),
  },
  {
    slug: "supplier-security",
    reference: "POL-005",
    title: "Supplier and Third-Party Security Policy",
    summary: "How security risk from suppliers and partners is assessed and managed through the relationship.",
    body: [
      "Purpose",
      "This policy describes how we manage the security risks that come with using suppliers and other third parties who handle our information or provide services to us.",
      "",
      "Scope",
      "It applies to any external organisation that stores, processes or has access to our information or systems, and to the people who own those relationships internally.",
      "",
      "Policy statements",
      "Before we engage a supplier who will handle sensitive information, we assess the security risk in proportion to what they will do for us. Security expectations are set out in the contract, including how our information is protected, who may access it, and what happens when the relationship ends. We give suppliers only the access they need and we keep a record of the relationships that carry meaningful risk. Supplier security is reviewed periodically during the relationship, and any incident on their side that affects our information must be reported to us promptly.",
      "",
      "Responsibilities",
      "Relationship owners are accountable for the security of the suppliers they manage. Procurement and legal ensure the right terms are in place. Security supports risk assessment and reviews.",
      "",
      "Review",
      "This policy is reviewed at least once a year and when our reliance on third parties changes materially.",
    ].join("\n"),
  },
  {
    slug: "business-continuity",
    reference: "POL-006",
    title: "Business Continuity Policy",
    summary: "How we keep critical activities running and recover after a disruptive event.",
    body: [
      "Purpose",
      "This policy sets out our commitment to keeping the activities that matter most running during a disruption and to recovering the rest in a planned way.",
      "",
      "Scope",
      "It applies to the people, processes, systems and locations that support our critical business activities.",
      "",
      "Policy statements",
      "We identify the activities that are critical to the business and understand how long they can be interrupted before the impact becomes serious. We maintain plans that describe how we would respond to a disruption, who is involved, and how we would communicate. Backups and alternative arrangements are in place for the systems and information our critical activities depend on. Our plans are tested at sensible intervals so that people know their roles and the plans stay workable. After a real disruption or a test, we capture what we learned and improve.",
      "",
      "Responsibilities",
      "Leadership owns continuity and provides the resources for it. Activity owners maintain and test the plans for their areas. IT maintains the technical recovery arrangements. Everyone follows the plans when they are invoked.",
      "",
      "Review",
      "This policy is reviewed at least once a year and after any significant disruption, test or business change.",
    ].join("\n"),
  },
  {
    slug: "data-protection",
    reference: "POL-007",
    title: "Data Protection and Privacy Policy",
    summary: "How personal data is handled lawfully, fairly and only for as long as it is needed.",
    body: [
      "Purpose",
      "This policy explains how we handle personal data so that we respect the rights of the people it relates to and meet our legal obligations.",
      "",
      "Scope",
      "It applies to all personal data we hold, however it is collected or stored, and to everyone who handles it on our behalf.",
      "",
      "Policy statements",
      "We collect personal data only for clear and lawful purposes and we use it only for those purposes. We collect no more than we need, keep it accurate, and retain it only for as long as there is a genuine reason to. Personal data is protected with controls that reflect how sensitive it is, and it is shared with others only where there is a proper basis to do so. We respect the rights of individuals to access and correct their data and to object to certain uses, and we respond to such requests within the required time. Any breach involving personal data is handled through our incident process and is notified where the law requires.",
      "",
      "Responsibilities",
      "Everyone who handles personal data must follow this policy. The person responsible for data protection provides guidance and oversees requests and breaches. Managers make sure their teams understand their obligations.",
      "",
      "Review",
      "This policy is reviewed at least once a year and whenever relevant law or our processing activities change.",
    ].join("\n"),
  },
  {
    slug: "cryptography",
    reference: "POL-008",
    title: "Cryptography Policy",
    summary: "When and how encryption and key management are used to protect information.",
    body: [
      "Purpose",
      "This policy sets out how we use encryption and manage cryptographic keys to protect information in storage and in transit.",
      "",
      "Scope",
      "It applies to all systems and services that hold or move information which needs protecting, and to the people who operate them.",
      "",
      "Policy statements",
      "We use encryption to protect sensitive information when it is stored and when it travels across networks, and we choose established, current algorithms rather than weak or outdated ones. Connections that carry confidential information are secured, and portable devices and removable media that hold sensitive data are encrypted. Cryptographic keys are generated, stored and retired in a controlled way, access to them is limited, and they are rotated or replaced when there is reason to. Where a key is lost or exposed, we treat it as a security incident.",
      "",
      "Responsibilities",
      "IT and system owners implement encryption and manage keys in line with this policy. Security advises on suitable methods and reviews their use. Users follow the controls provided, such as keeping device encryption enabled.",
      "",
      "Review",
      "This policy is reviewed at least once a year and when cryptographic standards or our systems change materially.",
    ].join("\n"),
  },
  {
    slug: "physical-security",
    reference: "POL-009",
    title: "Physical Security Policy",
    summary: "How premises, equipment and physical media are protected from unauthorised access and harm.",
    body: [
      "Purpose",
      "This policy describes how we protect our premises, equipment and physical records so that information is not lost, stolen or exposed through physical means.",
      "",
      "Scope",
      "It applies to all of our sites and work areas, the equipment kept there, and everyone who works in or visits them.",
      "",
      "Policy statements",
      "Access to our premises and to areas that hold sensitive equipment or information is limited to those who need it, and visitors are signed in and accompanied where appropriate. Equipment is sited and protected to reduce the risk of theft, damage and unauthorised viewing, and screens and papers are cleared away or locked when unattended. Sensitive physical records and media are stored securely and disposed of in a way that prevents recovery. People working away from our sites take reasonable care of the equipment and information in their charge. Loss or theft of equipment is reported through our incident process.",
      "",
      "Responsibilities",
      "Whoever manages a site is responsible for its physical controls. IT protects and disposes of equipment and media. Everyone secures the workspace and equipment they use.",
      "",
      "Review",
      "This policy is reviewed at least once a year and when our sites or working arrangements change significantly.",
    ].join("\n"),
  },
  {
    slug: "secure-development",
    reference: "POL-010",
    title: "Secure Development Policy",
    summary: "How security is built into the way we design, build, test and release software.",
    body: [
      "Purpose",
      "This policy sets out how we build security into the software we develop so that the systems we ship are trustworthy.",
      "",
      "Scope",
      "It applies to everyone involved in designing, building, testing or releasing our software and to the environments used to do so.",
      "",
      "Policy statements",
      "Security is considered from the start of a piece of work, and known risks are addressed as part of the design rather than bolted on later. Code is written with common weaknesses in mind, is reviewed before it is merged, and is checked with appropriate testing. Development, test and production environments are kept separate, and real sensitive data is not used carelessly in lower environments. Changes are tested and approved before they reach production, and the components and libraries we depend on are kept reasonably up to date and free of known serious flaws. Secrets and credentials are kept out of source code and are stored securely.",
      "",
      "Responsibilities",
      "Engineers build and review code in line with this policy. Technical leads make sure the practices are followed in their teams. Security provides guidance and reviews the approach.",
      "",
      "Review",
      "This policy is reviewed at least once a year and when our development tools or practices change materially.",
    ].join("\n"),
  },
];

export function policyTemplateBySlug(slug: string): PolicyTemplate | undefined {
  return POLICY_TEMPLATES.find((template) => template.slug === slug);
}
